def orderRowsAlphabet():
    archivo = open("texto.txt")
    lectura_archivo = archivo.read()
    lista_renglones = lectura_archivo.split("\n")
    archivo.close()
    renglon1 = lista_renglones[0].split(" ")
    renglon2 = lista_renglones[1].split(" ")
    renglon3 = lista_renglones[2].split(" ")
    renglon4 = lista_renglones[3].split(" ")
    renglon1.sort()
    renglon2.sort()
    renglon3.sort()
    renglon4.sort()
    print(renglon1)
    print(renglon2)
    print(renglon3)
    print(renglon4)

orderRowsAlphabet()